<?
  define('INCVER', 2);
  require_once 't7layout.php';
  $layout->start('photo album designer');
?>
      <p>
        This application was originally developed for track7, but has been
        enhanced to the point where it can be useful for anyone who would like
        to make an HTML photo album.&nbsp; The photo albums generated use HTML,
        Cascading Style Sheets (CSS), and JavaScript (JS) to create an
        interactive photo album with support for multiple pages, photo captions,
        and long photo descriptions.&nbsp; Version 2.2.0 and up use version 2 of
        the analog underground Common Controls--it cannot be installed at the
        same time as a version of MIM earlier than 1.3.0.
      </p>
      <ul>
        <li>see the Photo Album Designer in use:<ul>
          <li><a href="http://pictures.jmeagher.2ya.com/" title="visit a site generated by the Photo Album Designer">joe's index and links</a></li>
          <li><a href="http://jdhobby.dyndns.org/jeffhtml/" title="visit a site generated by the Photo Album Designer">jeff's pictures</a> (<a href="http://jdhobby.vze.com/">j&amp;d hobby</a>)</li>
          <li><a href="http://www.geo.mtu.edu/~kaburns/" title="visit a site generated by the Photo Album Designer">kirstin's photos</a></li>
        </ul></li>
      </ul>
<?
  $layout->end();
?>
