<?
/*----------------------------------------------------------------------------*\
 | title:    disc golf course-specific scorecard                              |
 | purpose:  generates a scorecard for the course specified, printing par for |
 |           each hole as well as some other course information.  the format  |
 |           is rtf instead of html to allow for easier printing.             |
 | notes:    will give a 404 error if no course is specified or if the course |
 |           specified cannot be found.                                       |
\*----------------------------------------------------------------------------*/
  define('FIRSTCELLWIDTH', 1440);  // 1 inch
  define('CELLWIDTH', 360);        // ¼ inch
  define('LASTCELLWIDTH', 720);     // ½ inch
  define('TOPMARGIN', 720);
  define('BOTTOMMARGIN', 720);
  define('PAGEWIDTH', FIRSTCELLWIDTH + 18 * CELLWIDTH + LASTCELLWIDTH);
  define('SIDEMARGIN', round((12240 - PAGEWIDTH) / 2 - .4));

  function startrow($thicktop = false, $thickbottom = false) {
    echo '{\trowd\trgaph0' . "\n";
    if($thicktop)
      $hborder = '\clbrdrt\brdrw30\brdrs';
    else
      $hborder = '\clbrdrt\brdrw10\brdrs';
    if($thickbottom)
      $hborder .= '\clbrdrb\brdrw30\brdrs';
    echo $hborder . '\clbrdrl\brdrw30\brdrs\clbrdrr\brdrw30\brdrs\cellx' . FIRSTCELLWIDTH . "\n";
    for($hole = 1; $hole < 9; $hole++)
      echo $hborder . '\clbrdrr\brdrw10\brdrs\cellx' . (FIRSTCELLWIDTH + CELLWIDTH * $hole) . "\n";
    echo $hborder . '\clbrdrr\brdrw30\brdrs\cellx' . (FIRSTCELLWIDTH + CELLWIDTH * 9) . "\n";
    for($hole = 10; $hole < 18; $hole++)
      echo $hborder . '\clbrdrr\brdrw10\brdrs\cellx' . (FIRSTCELLWIDTH + CELLWIDTH * $hole) . "\n";
    echo $hborder . '\clbrdrr\brdrw30\brdrs\cellx' . (FIRSTCELLWIDTH + CELLWIDTH * 18) . "\n";
    echo $hborder . '\clbrdrr\brdrw30\brdrs\cellx' . (FIRSTCELLWIDTH + CELLWIDTH * 18 + LASTCELLWIDTH) . "\n" . '\intbl' . "\n";
  }

  function cardheader($parlist, $par) {
    startrow(true);
?>
{\b\qr hole}\cell
{\b\qc
1\cell 2\cell 3\cell 4\cell 5\cell 6\cell 7\cell 8\cell 9\cell 10\cell 11\cell 12\cell 13\cell 14\cell 15\cell 16\cell 17\cell 18\cell
{\b total}\cell
}\row}
<?
    startrow();
?>
{\qr par}\cell
{\qc
<?
  for($hole = 0; $hole < 18; $hole++)
    echo $parlist[$hole] . '\cell ';
  echo "\n";
?>
{\b <?=$par; ?>}\cell
}\row}
<?
  }

  function scorecells() {
    startrow(true);
?>
\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell
\row}
<?
    startrow();
?>
\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\row
\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\row
\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\row
\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell
\row}
<?
    startrow(false, true);
?>
\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell\cell
\row}
<?
  }

  require_once dirname($_SERVER['DOCUMENT_ROOT']) . '/lib/track7.php';
  // if no course specified, give a 404 error
  if(!isset($_GET['course']) || !is_numeric($_GET['course']))
    $page->Show404();
  $course = 'select name, location, parlist, par, comments from dgcourses where id=' . $_GET['course'];
  $course = $db->Get($course);
  // if we can't find the course, give a 404 error
  if($course->IsError() || !($course = $course->NextRecord()))
    $page->Show404();
  // tell the browser that rtf is coming
  header('Content-type: text/rtf');
  $course->parlist = explode('|', $course->parlist);
?>
{\rtf1\ansi\deff0\margt<?=TOPMARGIN; ?>\margb<?=BOTTOMMARGIN; ?>\margl<?=SIDEMARGIN; ?>\margr<?=SIDEMARGIN; ?>

{\info
{\title <?=$course->name; ?> scorecard}
{\author \~}
{\company track7}
{\creatim\yr<?=date('Y'); ?>\mo<?=date('n'); ?>\dy<?=date('j'); ?>}
{\doccomm RTF generated by PHP}
}
{\fonttbl
{\f0\froman Georgia;}
}
\deflang1033\plain\fs22
{\footer\qr http://<?=$_SERVER['HTTP_HOST']; ?>/geek/discgolf/}
{\qc\f1\fs50\b
<?=$course->name; ?> \'96 <?=$course->location; ?>

\par}
{\sa90
<?=$course->comments; ?>

\par}
<?
  cardheader($course->parlist, $course->par);
  scorecells();
?>
{\pard \par}
<?
  cardheader($course->parlist, $course->par);
  scorecells();
?>
{\pard \par}
<?
  cardheader($course->parlist, $course->par);
  scorecells();
?>
{\pard \par}
<?
  cardheader($course->parlist, $course->par);
  scorecells();
?>
{\pard \par}
<?
  cardheader($course->parlist, $course->par);
  scorecells();
?>
}