<?
  require_once dirname($_SERVER['DOCUMENT_ROOT']) . '/lib/track7.php';
  require_once 'auFile.php';

  $page->Start('visual basic - the analog underground', 'visual basic');

  $page->Heading('<img src="pad.png" alt="" class="icon" />photo album designer', 'pad');
?>
      <p>
        This application was originally developed for track7, but has been
        enhanced to the point where it can be useful for anyone who would like
        to make an HTML photo album.&nbsp; The photo albums generated use HTML,
        Cascading Style Sheets (CSS), and JavaScript (JS) to create an
        interactive photo album with support for multiple pages, photo captions,
        and long photo descriptions.&nbsp; Version 2.2.0 and up use version 2 of
        the analog underground Common Controls--it cannot be installed at the
        same time as a version of MIM earlier than 1.3.0.
      </p>
      <ul>
        <li>see the Photo Album Designer in use:<ul>
          <li><a href="http://pictures.jmeagher.2ya.com/" title="visit a site generated by the Photo Album Designer">joe's index and links</a></li>
          <!--li><a href="http://jdhobby.dyndns.org:211/jdhobby/jeffhtml/" title="visit a site generated by the Photo Album Designer">jeff's pictures</a> (<a href="http://jdhobby.vze.com/">j&amp;d hobby</a>)</li-->
          <!--li><a href="http://www.geo.mtu.edu/~kaburns/">a thousand words</a></li-->
        </ul></li>
      </ul>
      <table class="data" cellspacing="0">
        <thead><tr><td class="clear"></td><th>installer</th><th>source</th></tr></thead>
        <tbody>
          <tr><td class="clear">2.4.0</td><td><a href="/files/analogu/vb/pad/pad_v2.4.0.zip" title="Photo Album Designer v2.4.0 installer"><?=auFile::Size('vb/pad/pad_v2.4.0.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v2.4.0.zip" title="Photo Album Designer v2.4.0 source"><?=auFile::Size('vb/pad/pad.source_v2.4.0.zip'); ?></a></td></tr>
          <tr><td class="clear">2.3.0</td><td><a href="/files/analogu/vb/pad/pad_v2.3.0.zip" title="Photo Album Designer v2.3.0 installer"><?=auFile::Size('vb/pad/pad_v2.3.0.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v2.3.0.zip" title="Photo Album Designer v2.3.0 source"><?=auFile::Size('vb/pad/pad.source_v2.3.0.zip'); ?></a></td></tr>
          <tr><td class="clear">2.2.0</td><td><a href="/files/analogu/vb/pad/pad_v2.2.0.zip" title="Photo Album Designer v2.2.0 installer"><?=auFile::Size('vb/pad/pad_v2.2.0.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v2.2.0.zip" title="Photo Album Designer v2.2.0 source"><?=auFile::Size('vb/pad/pad.source_v2.2.0.zip'); ?></a></td></tr>
          <tr><td class="clear">2.1.1</td><td><a href="/files/analogu/vb/pad/pad_v2.1.1.zip" title="Photo Album Designer v2.1.1 installer"><?=auFile::Size('vb/pad/pad_v2.1.1.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v2.1.1.zip" title="Photo Album Designer v2.1.1 source"><?=auFile::Size('vb/pad/pad.source_v2.1.1.zip'); ?></a></td></tr>
          <tr><td class="clear">2.0.0</td><td><a href="/files/analogu/vb/pad/pad_v2.0.0.zip" title="Photo Album Designer v2.0.0 installer"><?=auFile::Size('vb/pad/pad_v2.0.0.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v2.0.0.zip" title="Photo Album Designer v2.0.0 source"><?=auFile::Size('vb/pad/pad.source_v2.0.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.6.2</td><td><a href="/files/analogu/vb/pad/pad_v1.6.2.zip" title="Photo Album Designer v1.6.2 installer"><?=auFile::Size('vb/pad/pad_v1.6.2.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v1.6.2.zip" title="Photo Album Designer v1.6.2 source"><?=auFile::Size('vb/pad/pad.source_v1.6.2.zip'); ?></a></td></tr>
          <tr><td class="clear">1.5.4</td><td><a href="/files/analogu/vb/pad/pad_v1.5.4.zip" title="Photo Album Designer v1.5.4 installer"><?=auFile::Size('vb/pad/pad_v1.5.4.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v1.5.4.zip" title="Photo Album Designer v1.5.4 source"><?=auFile::Size('vb/pad/pad.source_v1.5.4.zip'); ?></a></td></tr>
          <tr><td class="clear">1.4.0</td><td><a href="/files/analogu/vb/pad/pad_v1.4.0.zip" title="Photo Album Designer v1.4.0 installer"><?=auFile::Size('vb/pad/pad_v1.4.0.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v1.4.0.zip" title="Photo Album Designer v1.4.0 source"><?=auFile::Size('vb/pad/pad.source_v1.4.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.2.1</td><td><a href="/files/analogu/vb/pad/pad_v1.2.1.zip" title="Photo Album Designer v1.2.1 installer"><?=auFile::Size('vb/pad/pad_v1.2.1.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v1.2.1.zip" title="Photo Album Designer v1.2.1 source"><?=auFile::Size('vb/pad/pad.source_v1.2.1.zip'); ?></a></td></tr>
          <tr><td class="clear">1.1.0</td><td><a href="/files/analogu/vb/pad/pad_v1.1.0.zip" title="Photo Album Designer v1.1.0 installer"><?=auFile::Size('vb/pad/pad_v1.1.0.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v1.1.0.zip" title="Photo Album Designer v1.1.0 source"><?=auFile::Size('vb/pad/pad.source_v1.1.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.0.9</td><td><a href="/files/analogu/vb/pad/pad_v1.0.9.zip" title="Photo Album Designer v1.0.9 installer"><?=auFile::Size('vb/pad/pad_v1.0.9.zip'); ?></a></td><td><a href="/files/analogu/vb/pad/pad.source_v1.0.9.zip" title="Photo Album Designer v1.0.9 source"><?=auFile::Size('vb/pad/pad.source_v1.0.9.zip'); ?></a></td></tr>
        </tbody>
      </table>

<?
  $page->Heading('<img src="mfe.png" alt="" class="icon" />movies front end', 'mfe');
?>
      <p>
        This application serves to help catalog movie collections that have been
        backed up to cd.&nbsp; It features an HTML export of the collection,
        reports on which movies need to be compressed to fit on a single cd, which
        are ready to be burned, and which are currently on the computer.&nbsp;
        Unfortunately this application will not run on a computer that does not
        have Microsoft Access 2002 (XP) installed.&nbsp; Anyone who has been using
        MFE is advised to download version 1.4.0 and use Export to MIM off the
        File menu.&nbsp; The .mim file created can be used with Movie Information
        Manager.
      </p>
      <table class="data" cellspacing="0">
        <thead><tr><td class="clear"></td><th>installer</th><th>source</th></tr></thead>
        <tbody>
          <tr><td class="clear">1.4.0</td><td><a href="/files/analogu/vb/mfe.zip" title="Movies Front End v1.4.0 installer"><?=auFile::Size('vb/mfe.zip'); ?></a></td><td><a href="/files/analogu/vb/mfe_src.zip" title="Movies Front End v1.4.0 source"><?=auFile::Size('vb/mfe_src.zip'); ?></a></td></tr>
        </tbody>
      </table>

<?
  $page->Heading('<img src="mim.png" alt="" class="icon" />movie information manager', 'mim');
?>
      <p>
        This application serves to help catalog movie collections that have been
        backed up to cd.&nbsp; It features an HTML export of the collection,
        reports on which movies need to be compressed to fit on a single cd, which
        are ready to be burned, and which are currently on the computer.&nbsp; MIM
        expands on MFE by allowing for more data to be collected, moving away from
        dependency on Microsoft Access 2002, and redesigning the user interface.&nbsp;
        Version 1.3.0 and up use version 2 of the analog underground Common
        Controls--it cannot be installed at the same time as a version of PAD
        earlier than 2.2.0.
      </p>
      <table class="data" cellspacing="0">
        <thead><tr><td class="clear"></td><th>installer</th><th>source</th></tr></thead>
        <tbody>
          <tr><td class="clear">1.3.1</td><td><a href="/files/analogu/vb/mim/mim_v1.3.1.zip" title="Movie Information Manager v1.3.1 installer"><?=auFile::Size('vb/mim/mim_v1.3.1.zip'); ?></a></td><td><a href="/files/analogu/vb/mim/mim.source_v1.3.1.zip" title="Movie Information Manager v1.3.1 source"><?=auFile::Size('vb/mim/mim.source_v1.3.1.zip'); ?></a></td></tr>
          <tr><td class="clear">1.2.0</td><td><a href="/files/analogu/vb/mim/mim_v1.2.0.zip" title="Movie Information Manager v1.2.0 installer"><?=auFile::Size('vb/mim/mim_v1.2.0.zip'); ?></a></td><td><a href="/files/analogu/vb/mim/mim.source_v1.2.0.zip" title="Movie Information Manager v1.2.0 source"><?=auFile::Size('vb/mim/mim.source_v1.2.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.1.0</td><td><a href="/files/analogu/vb/mim/mim_v1.1.0.zip" title="Movie Information Manager v1.1.0 installer"><?=auFile::Size('vb/mim/mim_v1.1.0.zip'); ?></a></td><td><a href="/files/analogu/vb/mim/mim.source_v1.1.0.zip" title="Movie Information Manager v1.1.0 source"><?=auFile::Size('vb/mim/mim.source_v1.1.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.0.0</td><td><a href="/files/analogu/vb/mim/mim_v1.0.0.zip" title="Movie Information Manager v1.0.0 installer"><?=auFile::Size('vb/mim/mim_v1.0.0.zip'); ?></a></td><td><a href="/files/analogu/vb/mim/mim.source_v1.0.0.zip" title="Movie Information Manager v1.0.0 source"><?=auFile::Size('vb/mim/mim.source_v1.0.0.zip'); ?></a></td></tr>
        </tbody>
      </table>

<?
  $page->Heading('<img src="ocx.png" alt="" class="icon" />the analog underground common controls', 'auComCtl');
?>
      <p>
        This is basically my first project using ActiveX, and it's just a
        component, not an application.&nbsp; It has two controls:&nbsp; a
        FileNameBox, and a NumberBox.&nbsp; Version 2.0.0 and forward also
        include a third control:&nbsp; FolderNameBox.&nbsp; All of these
        controls are used in Photo Album Designer and Movie Information Manager.&nbsp;
        If you want to use this component, you should be able to download and
        run the installer, or just install Photo Album Designer or Movie
        Information Manager.
      </p>
      <table class="data" cellspacing="0">
        <thead><tr><td class="clear"></td><th>installer</th><th>source</th></tr></thead>
        <tbody>
          <tr><td class="clear">2.0.0</td><td><a href="/files/analogu/vb/auComCtl/auComCtl_v2.0.0.zip" title="the analog underground Common Controls v2.0.0 installer"><?=auFile::Size('vb/auComCtl/auComCtl_v2.0.0.zip'); ?></a></td><td><a href="/files/analogu/vb/auComCtl/auComCtl.source_v2.0.0.zip" title="the analog underground Common Controls v2.0.0 source"><?=auFile::Size('vb/auComCtl/auComCtl.source_v2.0.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.4.2</td><td><a href="/files/analogu/vb/auComCtl/auComCtl_v1.4.2.zip" title="the analog underground Common Controls v1.4.2 installer"><?=auFile::Size('vb/auComCtl/auComCtl_v1.4.2.zip'); ?></a></td><td><a href="/files/analogu/vb/auComCtl/auComCtl.source_v1.4.2.zip" title="the analog underground Common Controls v1.4.2 source"><?=auFile::Size('vb/auComCtl/auComCtl.source_v1.4.2.zip'); ?></a></td></tr>
          <tr><td class="clear">1.3.0</td><td><a href="/files/analogu/vb/auComCtl/auComCtl_v1.3.0.zip" title="the analog underground Common Controls v1.3.0 installer"><?=auFile::Size('vb/auComCtl/auComCtl_v1.3.0.zip'); ?></a></td><td><a href="/files/analogu/vb/auComCtl/auComCtl.source_v1.3.0.zip" title="the analog underground Common Controls v1.3.0 source"><?=auFile::Size('vb/auComCtl/auComCtl.source_v1.3.0.zip'); ?></a></td></tr>
          <tr><td class="clear">1.2.1</td><td><a href="/files/analogu/vb/auComCtl/auComCtl_v1.2.1.zip" title="the analog underground Common Controls v1.2.1 installer"><?=auFile::Size('vb/auComCtl/auComCtl_v1.2.1.zip'); ?></a></td><td><a href="/files/analogu/vb/auComCtl/auComCtl.source_v1.2.1.zip" title="the analog underground Common Controls v1.2.1 source"><?=auFile::Size('vb/auComCtl/auComCtl.source_v1.2.1.zip'); ?></a></td></tr>
        </tbody>
      </table>

<?
  $page->End();
?>
